/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package behandel.boundary;

import behandel.control.BehandelingManager;
import behandel.entity.Behandeling;
import behandel.entity.Behandeling.Status;
import java.util.Date;
import praktijk.entity.Therapeut;

/**
 *
 * @author Nigel
 */
public class BehandelingGUI extends javax.swing.JFrame {

    /**
     * Creates new form ToevoegenGUI
     */
    private BehandelingManager manager;
    private OverzichtGUI overzichtGUI;
    private Behandeling behandeling;
    
    public BehandelingGUI(BehandelingManager manager, OverzichtGUI gui) {
        this.manager = manager;
        this.overzichtGUI = gui;
        initComponents();
        vulComboBoxen();
        
    }
    
    
    public BehandelingGUI(BehandelingManager manager, OverzichtGUI gui, int behandelingsID) {
        this.manager = manager;
        this.overzichtGUI = gui;
        initComponents();
        vulComboBoxen();
        
        behandeling = manager.getBehandeling(behandelingsID);
        bsnTextField.setText(Integer.toString(behandeling.getBurgerServiceNummer()));
        behandelingscodeTextField.setText(behandeling.getBehandelingscode());        
        fysiotherapeutComboBox.setSelectedItem(behandeling.getFysiotherapeutBSN());
        statusComboBox.setSelectedItem(behandeling.getStatus());
        opmerkingTextArea.setText(behandeling.getOpmerking());
    }
    
    private void vulComboBoxen() {
        for (Therapeut therapeut : manager.getTherapeuten()) {
            fysiotherapeutComboBox.addItem(therapeut.getBsn());
        }
        for (Behandeling.Status status : Behandeling.Status.values()) {
            statusComboBox.addItem(status.toString());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        bsnLabel = new javax.swing.JLabel();
        behandelingscodeLabel = new javax.swing.JLabel();
        fysiotherapeutLabel = new javax.swing.JLabel();
        beginTijdLabel = new javax.swing.JLabel();
        eindTijdLabel = new javax.swing.JLabel();
        bsnTextField = new javax.swing.JTextField();
        behandelingscodeTextField = new javax.swing.JTextField();
        beginTijdTextField = new javax.swing.JTextField();
        eindTijdTextField = new javax.swing.JTextField();
        OpslaanButton = new javax.swing.JButton();
        AnnulerenButton = new javax.swing.JButton();
        fysiotherapeutComboBox = new javax.swing.JComboBox();
        eindTijdLabel1 = new javax.swing.JLabel();
        eindTijdLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        opmerkingTextArea = new javax.swing.JTextArea();
        statusComboBox = new javax.swing.JComboBox();

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setText("jTextField1");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bsnLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bsnLabel.setText("BSN");

        behandelingscodeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        behandelingscodeLabel.setText("Behandelingscode");

        fysiotherapeutLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fysiotherapeutLabel.setText("Fysiotherapeut");

        beginTijdLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        beginTijdLabel.setText("Begin tijd");

        eindTijdLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eindTijdLabel.setText("Eind tijd");

        bsnTextField.setEditable(false);
        bsnTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        behandelingscodeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        beginTijdTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        eindTijdTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        OpslaanButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        OpslaanButton.setText("Opslaan");
        OpslaanButton.setMaximumSize(new java.awt.Dimension(111, 31));
        OpslaanButton.setMinimumSize(new java.awt.Dimension(111, 31));
        OpslaanButton.setPreferredSize(new java.awt.Dimension(111, 31));
        OpslaanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OpslaanButtonActionPerformed(evt);
            }
        });

        AnnulerenButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        AnnulerenButton.setText("Annuleren");
        AnnulerenButton.setPreferredSize(new java.awt.Dimension(111, 31));
        AnnulerenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnnulerenButtonActionPerformed(evt);
            }
        });

        fysiotherapeutComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        eindTijdLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eindTijdLabel1.setText("Status");

        eindTijdLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        eindTijdLabel2.setText("Opmerking");

        opmerkingTextArea.setColumns(20);
        opmerkingTextArea.setRows(5);
        jScrollPane1.setViewportView(opmerkingTextArea);

        statusComboBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bsnLabel)
                    .addComponent(eindTijdLabel)
                    .addComponent(beginTijdLabel)
                    .addComponent(fysiotherapeutLabel)
                    .addComponent(behandelingscodeLabel)
                    .addComponent(eindTijdLabel2)
                    .addComponent(eindTijdLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 128, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(OpslaanButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(AnnulerenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(statusComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bsnTextField, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(behandelingscodeTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addComponent(beginTijdTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addComponent(eindTijdTextField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                        .addComponent(fysiotherapeutComboBox, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bsnLabel)
                    .addComponent(bsnTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(behandelingscodeLabel)
                    .addComponent(behandelingscodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fysiotherapeutLabel)
                    .addComponent(fysiotherapeutComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(beginTijdLabel)
                    .addComponent(beginTijdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eindTijdLabel)
                    .addComponent(eindTijdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eindTijdLabel1)
                    .addComponent(statusComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(eindTijdLabel2)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(AnnulerenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OpslaanButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AnnulerenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnnulerenButtonActionPerformed
        overzichtGUI.setVisible(true);
        dispose();  
    }//GEN-LAST:event_AnnulerenButtonActionPerformed

    private void OpslaanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OpslaanButtonActionPerformed
        if (behandeling == null) {
           
        } else {
            int id = behandeling.getBehandelingsID();
            String code = behandelingscodeTextField.getText();
            long fysioBSN = Long.parseLong(fysiotherapeutComboBox.getSelectedItem().toString());
            Date begintijd = null;
            Date eindtijd = null;
            Status status = Status.valueOf(statusComboBox.getSelectedItem().toString());
            String opmerking = opmerkingTextArea.getText();
            
            manager.updateBehandeling(id, code, fysioBSN, begintijd, eindtijd, status, opmerking);
        }
    }//GEN-LAST:event_OpslaanButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BehandelingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BehandelingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BehandelingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BehandelingGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new BehandelingGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AnnulerenButton;
    private javax.swing.JButton OpslaanButton;
    private javax.swing.JLabel beginTijdLabel;
    private javax.swing.JTextField beginTijdTextField;
    private javax.swing.JLabel behandelingscodeLabel;
    private javax.swing.JTextField behandelingscodeTextField;
    private javax.swing.JLabel bsnLabel;
    private javax.swing.JTextField bsnTextField;
    private javax.swing.JLabel eindTijdLabel;
    private javax.swing.JLabel eindTijdLabel1;
    private javax.swing.JLabel eindTijdLabel2;
    private javax.swing.JTextField eindTijdTextField;
    private javax.swing.JComboBox fysiotherapeutComboBox;
    private javax.swing.JLabel fysiotherapeutLabel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextArea opmerkingTextArea;
    private javax.swing.JComboBox statusComboBox;
    // End of variables declaration//GEN-END:variables
}
