/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package behandel.boundary;

import behandel.control.BehandelingManager;
import behandel.entity.Behandeling;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Nigel
 */


public class OverzichtGUI extends javax.swing.JFrame {

    /**
     * Creates new form OverzichtGUI
     */
    private BehandelingManager manager;
    
    public OverzichtGUI(BehandelingManager manager) {
        this.manager = manager;
        if (!manager.isPatientenOpgehaald()) {
            JOptionPane.showMessageDialog(this, "<html>Het is niet gelukt om de patienten om te halen.<br>Daardoor is dit deelsysteem helaas niet beschikbaar.", "Fout", JOptionPane.ERROR_MESSAGE, null);
            return;
        }
        initComponents();
        updateTabel(); 
    }

    /**
     * Update de tabel
     */
    public void updateTabel() {
        ArrayList<Behandeling> behandelingen = manager.getBehandelingen();
        DefaultTableModel overzichtModel = (DefaultTableModel) overzichtTabelX.getModel();
        overzichtModel.setRowCount(0);
        
        for (Behandeling behandeling : behandelingen) {
            String deDatum = manager.formatDatum(behandeling.getBegintijd());
            String beginTijd = manager.formatTijd(behandeling.getBegintijd()); 
            String eindTijd = manager.formatTijd(behandeling.getEindtijd());
            overzichtModel.addRow(new Object[]{behandeling.getBehandelingsID(), behandeling.getBurgerServiceNummer(), behandeling.getFysiotherapeutBSN(), behandeling.getBehandelingscode(), deDatum, beginTijd, eindTijd, behandeling.getStatus(), behandeling.getOpmerking() });  
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        overzichtTabelX = new org.jdesktop.swingx.JXTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        toevoegenMenuItem = new javax.swing.JMenuItem();
        bewerkenMenuItem = new javax.swing.JMenuItem();
        verwijderMenuItem = new javax.swing.JMenuItem();
        terugMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        overzichtTabelX.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Patiënt BSN", "Fysiotherapeut BSN", "Behandelcode", "Datum", "Begin tijd", "Eind tijd", "Status", "Opmerking"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        overzichtTabelX.setEditable(false);
        overzichtTabelX.getTableHeader().setReorderingAllowed(false);
        overzichtTabelX.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                overzichtTabelXMouseReleased(evt);
            }
        });
        jScrollPane2.setViewportView(overzichtTabelX);
        overzichtTabelX.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        overzichtTabelX.getColumnModel().getColumn(0).setResizable(false);
        overzichtTabelX.getColumnModel().getColumn(0).setPreferredWidth(5);
        overzichtTabelX.getColumnModel().getColumn(1).setResizable(false);
        overzichtTabelX.getColumnModel().getColumn(1).setPreferredWidth(9);
        overzichtTabelX.getColumnModel().getColumn(2).setResizable(false);
        overzichtTabelX.getColumnModel().getColumn(2).setPreferredWidth(9);
        overzichtTabelX.getColumnModel().getColumn(3).setResizable(false);
        overzichtTabelX.getColumnModel().getColumn(3).setPreferredWidth(5);
        overzichtTabelX.getColumnModel().getColumn(4).setResizable(false);
        overzichtTabelX.getColumnModel().getColumn(4).setPreferredWidth(10);
        overzichtTabelX.getColumnModel().getColumn(5).setResizable(false);
        overzichtTabelX.getColumnModel().getColumn(5).setPreferredWidth(5);
        overzichtTabelX.getColumnModel().getColumn(6).setResizable(false);
        overzichtTabelX.getColumnModel().getColumn(6).setPreferredWidth(5);
        overzichtTabelX.getColumnModel().getColumn(7).setResizable(false);
        overzichtTabelX.getColumnModel().getColumn(7).setPreferredWidth(10);
        overzichtTabelX.getColumnModel().getColumn(8).setResizable(false);
        overzichtTabelX.getColumnModel().getColumn(8).setPreferredWidth(30);

        fileMenu.setText("File");

        toevoegenMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_T, java.awt.event.InputEvent.CTRL_MASK));
        toevoegenMenuItem.setActionCommand("Toevoegen");
        toevoegenMenuItem.setLabel("Toevoegen");
        toevoegenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toevoegenMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(toevoegenMenuItem);

        bewerkenMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        bewerkenMenuItem.setText("Bewerken");
        bewerkenMenuItem.setEnabled(false);
        bewerkenMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bewerkenMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(bewerkenMenuItem);

        verwijderMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        verwijderMenuItem.setText("Verwijderen");
        verwijderMenuItem.setEnabled(false);
        verwijderMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verwijderMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(verwijderMenuItem);

        terugMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.CTRL_MASK));
        terugMenuItem.setLabel("Terug");
        terugMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terugMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(terugMenuItem);

        jMenuBar1.add(fileMenu);

        helpMenu.setText("Help");

        aboutMenuItem.setText("About");
        helpMenu.add(aboutMenuItem);

        jMenuBar1.add(helpMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1302, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 639, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void terugMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terugMenuItemActionPerformed
        //new HomeGUI().setVisible(true);
        
    }//GEN-LAST:event_terugMenuItemActionPerformed

    private void verwijderMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verwijderMenuItemActionPerformed
        int result = JOptionPane.showOptionDialog(this, "Wilt u deze behandeling echt verwijderen?", "Behandeling verwijderen", 0, JOptionPane.INFORMATION_MESSAGE, null, new String[]{"Ja", "Nee"}, "default");
        if(result == 0){
            manager.deleteBehandeling(getSelectedBehandelingID());    
            updateTabel();
        }
    }//GEN-LAST:event_verwijderMenuItemActionPerformed

    private void toevoegenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toevoegenMenuItemActionPerformed
        new BehandelingGUI(manager, this).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_toevoegenMenuItemActionPerformed

    private void bewerkenMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bewerkenMenuItemActionPerformed
        new BehandelingGUI(manager, this, getSelectedBehandelingID()).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_bewerkenMenuItemActionPerformed

    private void overzichtTabelXMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_overzichtTabelXMouseReleased
        try {
            System.out.println(getSelectedBehandelingID()); //Probeer een row te selecten
        } catch (ArrayIndexOutOfBoundsException e) {
            return;
        }
        bewerkenMenuItem.setEnabled(true);
        verwijderMenuItem.setEnabled(true);
    }//GEN-LAST:event_overzichtTabelXMouseReleased

    /**
     * Haal het ID op van de geselecteerde behandeling
     * @return het ID
     */
    private int getSelectedBehandelingID() {
        int row = overzichtTabelX.getSelectedRow();
        row = overzichtTabelX.convertRowIndexToModel(row);
        return (int) overzichtTabelX.getModel().getValueAt(row, 0);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OverzichtGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OverzichtGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OverzichtGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OverzichtGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new OverzichtGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem bewerkenMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTable overzichtTabelX;
    private javax.swing.JMenuItem terugMenuItem;
    private javax.swing.JMenuItem toevoegenMenuItem;
    private javax.swing.JMenuItem verwijderMenuItem;
    // End of variables declaration//GEN-END:variables
}
