/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package behandel.boundary;

import behandel.control.BehandelingManager;

/**
 *
 * @author Nigel
 */
public class ToevoegenGUI extends javax.swing.JFrame {

    /**
     * Creates new form ToevoegenGUI
     */
    private BehandelingManager manager;
    
    public ToevoegenGUI() {
        initComponents();
        manager = new BehandelingManager(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextField2 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        sofinummerLabel = new javax.swing.JLabel();
        behandelingscodeLabel = new javax.swing.JLabel();
        fysiotherapeutLabel = new javax.swing.JLabel();
        datumLabel = new javax.swing.JLabel();
        tijdLabel = new javax.swing.JLabel();
        sofinummerTextField = new javax.swing.JTextField();
        behandelingscodeTextField = new javax.swing.JTextField();
        datumTextField = new javax.swing.JTextField();
        tijdTextField = new javax.swing.JTextField();
        opslaanButton = new javax.swing.JButton();
        annulerenButton = new javax.swing.JButton();
        fysiotherapeutBox = new javax.swing.JComboBox();

        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField2.setText("jTextField1");

        jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTextField5.setText("jTextField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        sofinummerLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        sofinummerLabel.setText("Sofinummer");

        behandelingscodeLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        behandelingscodeLabel.setText("Behandelingscode");

        fysiotherapeutLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fysiotherapeutLabel.setText("Fysiotherapeut");

        datumLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        datumLabel.setText("Datum");

        tijdLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        tijdLabel.setText("Tijd");

        sofinummerTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        behandelingscodeTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        datumTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        tijdTextField.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        opslaanButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        opslaanButton.setText("Opslaan");
        opslaanButton.setMaximumSize(new java.awt.Dimension(111, 31));
        opslaanButton.setMinimumSize(new java.awt.Dimension(111, 31));
        opslaanButton.setPreferredSize(new java.awt.Dimension(111, 31));

        annulerenButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        annulerenButton.setText("Annuleren");
        annulerenButton.setPreferredSize(new java.awt.Dimension(111, 31));
        annulerenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerenButtonActionPerformed(evt);
            }
        });

        fysiotherapeutBox.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        fysiotherapeutBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Kees", "Jan", "Piet", "Tafel" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sofinummerLabel)
                    .addComponent(tijdLabel)
                    .addComponent(datumLabel)
                    .addComponent(fysiotherapeutLabel)
                    .addComponent(behandelingscodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(sofinummerTextField)
                    .addComponent(behandelingscodeTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(datumTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(tijdTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                    .addComponent(fysiotherapeutBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(186, Short.MAX_VALUE)
                .addComponent(opslaanButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(annulerenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sofinummerLabel)
                    .addComponent(sofinummerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(behandelingscodeLabel)
                    .addComponent(behandelingscodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fysiotherapeutLabel)
                    .addComponent(fysiotherapeutBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(datumLabel)
                    .addComponent(datumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tijdLabel)
                    .addComponent(tijdTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(annulerenButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(opslaanButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerenButtonActionPerformed
        new OverzichtGUI().setVisible(true);
        dispose();  
    }//GEN-LAST:event_annulerenButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ToevoegenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ToevoegenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ToevoegenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ToevoegenGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ToevoegenGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerenButton;
    private javax.swing.JLabel behandelingscodeLabel;
    private javax.swing.JTextField behandelingscodeTextField;
    private javax.swing.JLabel datumLabel;
    private javax.swing.JTextField datumTextField;
    private javax.swing.JComboBox fysiotherapeutBox;
    private javax.swing.JLabel fysiotherapeutLabel;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JButton opslaanButton;
    private javax.swing.JLabel sofinummerLabel;
    private javax.swing.JTextField sofinummerTextField;
    private javax.swing.JLabel tijdLabel;
    private javax.swing.JTextField tijdTextField;
    // End of variables declaration//GEN-END:variables
}
