/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package rapportage.boundary;

import behandel.control.BehandelingManager;
import home.boundary.HomeGUI;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import rapportage.control.PlanningControl;

/**
 *
 * @author Jan
 */
public class PlanningGUI extends javax.swing.JFrame {

    private String separator = System.getProperty("file.separator");
    private HomeGUI homeGUI;
    private PlanningControl control;

    /**
     * Creates new form PlanningGUI
     */
    public PlanningGUI(HomeGUI homeGUI, BehandelingManager manager) {
        this.homeGUI = homeGUI;
        initComponents();
        control = new PlanningControl((DefaultTableModel) overzichtTabel.getModel(), manager);
        this.setExtendedState(this.MAXIMIZED_BOTH);
        control.getGegevens(new Date(new Date().getTime() - 84600000), new Date(new Date().getTime() + 86400000), (DefaultTableModel) overzichtTabel.getModel());

        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                sluitGUI();
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        inhoudPanel = new javax.swing.JPanel();
        datumButton = new javax.swing.JButton();
        sofinummerTextField = new javax.swing.JTextField();
        sofinummerButton = new javax.swing.JButton();
        terugButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        overzichtTabel = new org.jdesktop.swingx.JXTable();
        startdatumTextField = new org.jdesktop.swingx.JXDatePicker();
        einddatumTextField = new org.jdesktop.swingx.JXDatePicker();
        jMenuBar1 = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        terugMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        datumButton.setText("Zoek op datum");
        datumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datumButtonActionPerformed(evt);
            }
        });

        sofinummerTextField.setText("Sofinummer");

        sofinummerButton.setText("Zoek op Sofinummer");
        sofinummerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sofinummerButtonActionPerformed(evt);
            }
        });

        terugButton.setText("Terug");
        terugButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terugButtonActionPerformed(evt);
            }
        });

        overzichtTabel.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Bedrijfscode", "TherapeutCode", "Sofinummer", "BehandelCode", "Datum", "Opmerkingen"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(overzichtTabel);
        overzichtTabel.getColumnModel().getColumn(0).setResizable(false);
        overzichtTabel.getColumnModel().getColumn(1).setResizable(false);
        overzichtTabel.getColumnModel().getColumn(2).setResizable(false);
        overzichtTabel.getColumnModel().getColumn(3).setResizable(false);
        overzichtTabel.getColumnModel().getColumn(4).setResizable(false);
        overzichtTabel.getColumnModel().getColumn(5).setResizable(false);

        javax.swing.GroupLayout inhoudPanelLayout = new javax.swing.GroupLayout(inhoudPanel);
        inhoudPanel.setLayout(inhoudPanelLayout);
        inhoudPanelLayout.setHorizontalGroup(
            inhoudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inhoudPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inhoudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(datumButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(sofinummerTextField)
                    .addComponent(sofinummerButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(startdatumTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(einddatumTextField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 583, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(terugButton, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        inhoudPanelLayout.setVerticalGroup(
            inhoudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inhoudPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inhoudPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, inhoudPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(terugButton))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 362, Short.MAX_VALUE)
                    .addGroup(inhoudPanelLayout.createSequentialGroup()
                        .addComponent(startdatumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(einddatumTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(datumButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sofinummerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sofinummerButton)))
                .addContainerGap())
        );

        fileMenu.setText("File");

        terugMenuItem.setLabel("Terug");
        terugMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                terugMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(terugMenuItem);

        jMenuBar1.add(fileMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inhoudPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(inhoudPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void datumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datumButtonActionPerformed
        boolean b = control.zoekDatum(startdatumTextField.getDate(), einddatumTextField.getDate(), (DefaultTableModel) overzichtTabel.getModel());
        if (b == true) {
            overzichtTabel.setModel(control.getModel());
        } else {
            JOptionPane.showMessageDialog(this, "Zoeken op datum is niet geslaagd.");
        }
    }//GEN-LAST:event_datumButtonActionPerformed

    private void sofinummerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sofinummerButtonActionPerformed
        boolean b = control.zoekSofinummer(Integer.parseInt(sofinummerTextField.getText()), (DefaultTableModel) overzichtTabel.getModel());
        if (b == true) {
            overzichtTabel.setModel(control.getModel());
        } else {
            JOptionPane.showMessageDialog(this, "Zoeken op sofinummer is niet geslaagd.");
        }
    }//GEN-LAST:event_sofinummerButtonActionPerformed

    private void terugMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terugMenuItemActionPerformed
        sluitGUI();
    }//GEN-LAST:event_terugMenuItemActionPerformed

    private void terugButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_terugButtonActionPerformed
        sluitGUI();
    }//GEN-LAST:event_terugButtonActionPerformed

    private void sluitGUI() {
        homeGUI.maakZichtbaar();
        dispose();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton datumButton;
    private org.jdesktop.swingx.JXDatePicker einddatumTextField;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JPanel inhoudPanel;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane2;
    private org.jdesktop.swingx.JXTable overzichtTabel;
    private javax.swing.JButton sofinummerButton;
    private javax.swing.JTextField sofinummerTextField;
    private org.jdesktop.swingx.JXDatePicker startdatumTextField;
    private javax.swing.JButton terugButton;
    private javax.swing.JMenuItem terugMenuItem;
    // End of variables declaration//GEN-END:variables
}
