package praktijk.boundary;

import java.text.NumberFormat;
import javax.swing.JOptionPane;
import praktijk.control.PraktijkManager;
import praktijk.entity.Praktijk;

/**
 *
 * @author Leon
 */
public class PraktijkWijzigGUI extends javax.swing.JFrame {
    private PraktijkManager manager;
    private PraktijkOverzichtGUI overzichtGUI;
    private int index;
    private Praktijk wijzigPraktijk;
    private boolean isNieuw;
    private NumberFormat format;

    /**
     * Creates new form PraktijkWijzigGUI
     */
    public PraktijkWijzigGUI(PraktijkOverzichtGUI overzicht, PraktijkManager manager) {
        format = NumberFormat.getNumberInstance();
        initComponents();
        this.manager = manager;
        this.overzichtGUI = overzicht;
        this.isNieuw = true;
        
        this.setTitle("Praktijk toevoegen");
    }
    
    public PraktijkWijzigGUI(PraktijkOverzichtGUI overzicht, PraktijkManager manager, int index) {
        format = NumberFormat.getNumberInstance();
        initComponents();
        
        this.manager = manager;
        this.overzichtGUI = overzicht;
        this.index = index;
        this.isNieuw = false;
        this.wijzigPraktijk = manager.getPraktijk(index);
        
        kvkFormattedField.setEnabled(false);
        this.setTitle("Praktijk wijzigen");
        vulVelden();
        
    }
    
    private void vulVelden() {
        naamTextField.setText(wijzigPraktijk.getNaam());
        plaatsTextField.setText(wijzigPraktijk.getPlaats());
        postcodeTextField.setText(wijzigPraktijk.getPostcode());
        huisnrTextField.setText(wijzigPraktijk.getHuisnummer());
        kvkFormattedField.setText(String.valueOf(wijzigPraktijk.getKvk()));
        ibannrTextField.setText(wijzigPraktijk.getIban());
        telefoonnrFormattedField.setText(String.valueOf(wijzigPraktijk.getTelnr()));
        faxnrFormattedField.setText(String.valueOf(wijzigPraktijk.getFaxnr()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        naamTextField = new javax.swing.JTextField();
        praktijkNaamLabel = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        plaatsTextField = new javax.swing.JTextField();
        postcodeTextField = new javax.swing.JTextField();
        huisnrTextField = new javax.swing.JTextField();
        ibannrTextField = new javax.swing.JTextField();
        annulerenButton = new javax.swing.JButton();
        opslaanButton = new javax.swing.JButton();
        kvkFormattedField = new javax.swing.JFormattedTextField(format);
        telefoonnrFormattedField = new javax.swing.JFormattedTextField(format);
        faxnrFormattedField = new javax.swing.JFormattedTextField(format);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        praktijkNaamLabel.setText("Naam");

        jLabel2.setText("Plaats");

        jLabel1.setText("Postcode");

        jLabel3.setText("Huisnummer");

        jLabel4.setText("KVK-nummer");

        jLabel5.setText("IBAN-nummer");

        jLabel6.setText("Telefoonnummer");

        jLabel7.setText("Faxnummer");

        annulerenButton.setText("Annuleren");
        annulerenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerenButtonActionPerformed(evt);
            }
        });

        opslaanButton.setText("Opslaan");
        opslaanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opslaanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(praktijkNaamLabel)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opslaanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(annulerenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ibannrTextField)
                    .addComponent(huisnrTextField)
                    .addComponent(naamTextField)
                    .addComponent(plaatsTextField)
                    .addComponent(postcodeTextField)
                    .addComponent(kvkFormattedField)
                    .addComponent(telefoonnrFormattedField)
                    .addComponent(faxnrFormattedField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(praktijkNaamLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plaatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(huisnrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kvkFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibannrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoonnrFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faxnrFormattedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opslaanButton)
                    .addComponent(annulerenButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void annulerenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerenButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_annulerenButtonActionPerformed

    private void opslaanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opslaanButtonActionPerformed
        if (!naamTextField.getText().isEmpty() && !plaatsTextField.getText().isEmpty() && !postcodeTextField.getText().isEmpty() && !huisnrTextField.getText().isEmpty() && !kvkFormattedField.getText().isEmpty() && !ibannrTextField.getText().isEmpty() && !telefoonnrFormattedField.getText().isEmpty() && !faxnrFormattedField.getText().isEmpty()) {
            String naam = naamTextField.getText();
            String plaats = plaatsTextField.getText();
            String postcode = postcodeTextField.getText();
            String huisnr = huisnrTextField.getText();
            long kvknr = Long.parseLong(kvkFormattedField.getText());
            String iban = ibannrTextField.getText();
            long telefoonnr = Long.parseLong(telefoonnrFormattedField.getText());
            long faxnr = Long.parseLong(faxnrFormattedField.getText());

            Praktijk praktijk = new Praktijk(naam, plaats, postcode, huisnr, kvknr, iban, telefoonnr, faxnr);
            boolean succes;
            
            if(isNieuw) {
                succes = manager.voegToe(praktijk);
            }
            else {
                succes = manager.wijzig(index, praktijk);
            }

            if (succes) {
                overzichtGUI.vernieuwOverzicht();
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(this, "Er is een fout opgetreden bij het opslaan van de praktijk.", "Fout", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Controleer of alle velden (correct) ingevuld zijn.", "Fout", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_opslaanButtonActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerenButton;
    private javax.swing.JFormattedTextField faxnrFormattedField;
    private javax.swing.JTextField huisnrTextField;
    private javax.swing.JTextField ibannrTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JFormattedTextField kvkFormattedField;
    private javax.swing.JTextField naamTextField;
    private javax.swing.JButton opslaanButton;
    private javax.swing.JTextField plaatsTextField;
    private javax.swing.JTextField postcodeTextField;
    private javax.swing.JLabel praktijkNaamLabel;
    private javax.swing.JFormattedTextField telefoonnrFormattedField;
    // End of variables declaration//GEN-END:variables
}
