package praktijk.boundary;

import home.control.IconManager;
import java.awt.Color;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.border.Border;
import javax.swing.border.LineBorder;
import praktijk.control.PraktijkManager;
import praktijk.entity.Praktijk;

/**
 *
 * @author Leon
 */
public class PraktijkWijzigGUI extends javax.swing.JFrame {
    private PraktijkManager manager;
    private PraktijkOverzichtGUI overzichtGUI;
    private int index;
    private Praktijk wijzigPraktijk;
    private boolean isNieuw;
    private boolean allesGeldig;

    /**
     * Constructor voor het toevoegen van een praktijk
     * @param overzicht het praktijkoverzicht dat vernieuwd dient te worden
     * @param manager de manager voor het lezen en schrijven van objecten
     */
    public PraktijkWijzigGUI(PraktijkOverzichtGUI overzicht, PraktijkManager manager) {
        initComponents();
        this.manager = manager;
        this.overzichtGUI = overzicht;
        this.isNieuw = true;
        
        setupFrame();
        this.setTitle("Praktijk toevoegen");
    }
    
    /**
     * Constructor voor het wijzigen van een praktijk
     * @param overzicht het praktijkoverzicht dat vernieuwd dient te worden
     * @param manager de manager voor het lezen en schrijven van objecten
     * @param index index van de te wijzigen praktijk
     */
    public PraktijkWijzigGUI(PraktijkOverzichtGUI overzicht, PraktijkManager manager, int index) {
        initComponents();
        this.manager = manager;
        this.overzichtGUI = overzicht;
        this.index = index;
        this.isNieuw = false;
        this.wijzigPraktijk = manager.getPraktijk(index);
        
        setupFrame();
        kvkNummerTextField.setEnabled(false);
        this.setTitle("Praktijk wijzigen");
        vulVelden();
    }
    
    /**
     * 
     */
    private void setupFrame() {
        IconManager.setIcon(this);
        
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                closeWindow();
            }
        });
    }
    
    /**
     * Vult alle velden in met geselecteerde praktijk data
     */
    private void vulVelden() {
        naamTextField.setText(wijzigPraktijk.getNaam());
        plaatsTextField.setText(wijzigPraktijk.getPlaats());
        postcodeTextField.setText(wijzigPraktijk.getPostcode());
        huisnrTextField.setText(wijzigPraktijk.getHuisnummer());
        kvkNummerTextField.setText(String.valueOf(wijzigPraktijk.getKvk()));
        ibannrTextField.setText(wijzigPraktijk.getIban());
        telefoonnummerTextField.setText(String.valueOf(wijzigPraktijk.getTelnr()));
        faxnummerTextField.setText(String.valueOf(wijzigPraktijk.getFaxnr()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        naamTextField = new javax.swing.JTextField();
        naamLabel = new javax.swing.JLabel();
        plaatsLabel = new javax.swing.JLabel();
        postcodeLabel = new javax.swing.JLabel();
        huisnummerLabel = new javax.swing.JLabel();
        kvkLabel = new javax.swing.JLabel();
        ibanLabel = new javax.swing.JLabel();
        telnrLabel = new javax.swing.JLabel();
        faxnrLabel = new javax.swing.JLabel();
        plaatsTextField = new javax.swing.JTextField();
        postcodeTextField = new javax.swing.JTextField();
        huisnrTextField = new javax.swing.JTextField();
        ibannrTextField = new javax.swing.JTextField();
        annulerenButton = new javax.swing.JButton();
        opslaanButton = new javax.swing.JButton();
        kvkNummerTextField = new javax.swing.JTextField();
        telefoonnummerTextField = new javax.swing.JTextField();
        faxnummerTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        naamLabel.setText("Naam");

        plaatsLabel.setText("Plaats");

        postcodeLabel.setText("Postcode");

        huisnummerLabel.setText("Huisnummer");

        kvkLabel.setText("KVK-nummer");

        ibanLabel.setText("IBAN-nummer");

        telnrLabel.setText("Telefoonnummer");

        faxnrLabel.setText("Faxnummer");

        annulerenButton.setText("Annuleren");
        annulerenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                annulerenButtonActionPerformed(evt);
            }
        });

        opslaanButton.setText("Opslaan");
        opslaanButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                opslaanButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(naamLabel)
                    .addComponent(plaatsLabel)
                    .addComponent(huisnummerLabel)
                    .addComponent(kvkLabel)
                    .addComponent(telnrLabel)
                    .addComponent(faxnrLabel)
                    .addComponent(postcodeLabel)
                    .addComponent(ibanLabel))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(opslaanButton, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(annulerenButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ibannrTextField)
                    .addComponent(huisnrTextField)
                    .addComponent(naamTextField)
                    .addComponent(plaatsTextField)
                    .addComponent(postcodeTextField)
                    .addComponent(kvkNummerTextField)
                    .addComponent(telefoonnummerTextField)
                    .addComponent(faxnummerTextField))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(naamTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(naamLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(plaatsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(plaatsLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(postcodeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(postcodeLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(huisnrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(huisnummerLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kvkNummerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kvkLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ibannrTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ibanLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(telefoonnummerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telnrLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(faxnrLabel)
                    .addComponent(faxnummerTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(opslaanButton)
                    .addComponent(annulerenButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Sluit het venster
     * @param evt 
     */
    private void annulerenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_annulerenButtonActionPerformed
        closeWindow();
    }//GEN-LAST:event_annulerenButtonActionPerformed

    /**
     * Maakt een nieuwe praktijk aan of wijzigt de gegevens van een bestaande praktijk. Ook worden alle gegevens geconroleerd.
     * @param evt 
     */
    private void opslaanButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_opslaanButtonActionPerformed
        String naam = naamTextField.getText();
        String plaats = plaatsTextField.getText();
        String postcode = postcodeTextField.getText().replace(" ", "");
        String huisnr = huisnrTextField.getText();
        String kvkStr = kvkNummerTextField.getText();
        String iban = ibannrTextField.getText().replace(" ", "");
        String telnr = telefoonnummerTextField.getText();
        String faxnr = faxnummerTextField.getText().replace(" ", "").replace("-", "");
        
        allesGeldig = true;
        
        checkGeldig(!naam.isEmpty(), naamLabel);
        checkGeldig(!plaats.isEmpty(), plaatsLabel);
        checkGeldig(postcode.matches("\\d{4}[a-zA-Z]{2}"), postcodeLabel);
        checkGeldig(huisnr.matches("\\d{1,}[a-zA-Z]?"), huisnummerLabel);
        checkGeldig(kvkStr.matches("\\d{8}"), kvkLabel);
        checkGeldig(iban.matches("[a-zA-Z]{2}\\d{2}[a-zA-Z]{4}\\d{10}"), ibanLabel);
        checkGeldig(telnr.replace(" ", "").replace("-", "").matches("(\\d{10})|(\\+\\d{11})"), telnrLabel);
        checkGeldig(faxnr.matches("\\d{10}"), faxnrLabel);
        
        if (allesGeldig) {
            long kvknr = Long.parseLong(kvkStr);

            if (isNieuw && manager.kvkBestaat(kvknr)) {
                JOptionPane.showMessageDialog(this, "Er bestaat reeds een praktijk met ditzelfde KVK-nummer.\nHet KVK-nummer dient uniek te zijn, pas eventueel de andere praktijk aan.", "Fout", JOptionPane.ERROR_MESSAGE);
                checkGeldig(false, kvkLabel);
                return;
            }

            Praktijk praktijk = new Praktijk(naam, plaats, postcode, huisnr, kvknr, iban, telnr, faxnr);
            boolean succes;
            
            if(isNieuw) {
                succes = manager.voegToe(praktijk);
            }
            else {
                succes = manager.wijzig(index, praktijk);
            }

            if (succes) {
                overzichtGUI.vernieuwOverzicht();
                this.dispose();
            }
            else {
                JOptionPane.showMessageDialog(this, "Er is een fout opgetreden bij het opslaan van de praktijk.", "Fout", JOptionPane.ERROR_MESSAGE);
            }
        }
        else {
            JOptionPane.showMessageDialog(this, "Controleer of alle velden (correct) ingevuld zijn.\nFoutief ingevulde velden zijn rood weergegeven.", "Fout", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_opslaanButtonActionPerformed

    /**
     * Controleerd of het veld goed ingevuld is.<br />
     * Zo ja dan wordt het label zwart gekleurd. Zo nee, dan wordt het label rood gekleurd en het opslaan verhinderd.
     * @param geldig of het veld goed ingevuld is
     * @param label label dat bij het veld hoort
     */
    private void checkGeldig(boolean geldig, JLabel label) {
        if (geldig) {
            label.setForeground(Color.BLACK);
        }
        else {
            label.setForeground(Color.RED);
            allesGeldig = false;
        }
    }
    
    /**
     * Vraagt een bevestiging of het scherm gesloten moet worden
     */
    private void closeWindow() {
        int dialogResult = JOptionPane.showConfirmDialog(null, "Weet u zeker dat u dit scherm wilt sluiten zonder op te slaan?", "Sluiten", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            this.dispose();
        }
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton annulerenButton;
    private javax.swing.JLabel faxnrLabel;
    private javax.swing.JTextField faxnummerTextField;
    private javax.swing.JTextField huisnrTextField;
    private javax.swing.JLabel huisnummerLabel;
    private javax.swing.JLabel ibanLabel;
    private javax.swing.JTextField ibannrTextField;
    private javax.swing.JLabel kvkLabel;
    private javax.swing.JTextField kvkNummerTextField;
    private javax.swing.JLabel naamLabel;
    private javax.swing.JTextField naamTextField;
    private javax.swing.JButton opslaanButton;
    private javax.swing.JLabel plaatsLabel;
    private javax.swing.JTextField plaatsTextField;
    private javax.swing.JLabel postcodeLabel;
    private javax.swing.JTextField postcodeTextField;
    private javax.swing.JTextField telefoonnummerTextField;
    private javax.swing.JLabel telnrLabel;
    // End of variables declaration//GEN-END:variables
}
