/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import behandel.boundary.OverzichtGUI;
import praktijk.boundary.PraktijkOverzichtGUI;
import rapportage.boundary.CumulatiefGUI;
import rapportage.boundary.PlanningGUI;
import rapportage.boundary.RoosterGUI;

/**
 *
 * @author Nigel
 */
public class HomeGUI extends javax.swing.JFrame {

    /**
     * Creates new form HomeGUI
     */
    public HomeGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        praktijkButton = new javax.swing.JButton();
        therapeutenButton = new javax.swing.JButton();
        roosterButton = new javax.swing.JButton();
        behandelingButton = new javax.swing.JButton();
        geplandeButton = new javax.swing.JButton();
        cumulatiefButton = new javax.swing.JButton();

        jInternalFrame1.setVisible(true);

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        praktijkButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        praktijkButton.setText("Praktijk overzicht");
        praktijkButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                praktijkButtonActionPerformed(evt);
            }
        });

        therapeutenButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        therapeutenButton.setText("Therapeuten overzicht");

        roosterButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        roosterButton.setText("Rooster fysiotherapeuten");
        roosterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roosterButtonActionPerformed(evt);
            }
        });

        behandelingButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        behandelingButton.setText("Behandeling overzicht");
        behandelingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                behandelingButtonActionPerformed(evt);
            }
        });

        geplandeButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        geplandeButton.setText("Overzicht geplande behandelingen");
        geplandeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geplandeButtonActionPerformed(evt);
            }
        });

        cumulatiefButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cumulatiefButton.setText("Cumulatief overzicht behandelingen");
        cumulatiefButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cumulatiefButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(geplandeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(cumulatiefButton, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(roosterButton, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(behandelingButton, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(therapeutenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(praktijkButton, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(praktijkButton)
                .addGap(40, 40, 40)
                .addComponent(therapeutenButton)
                .addGap(40, 40, 40)
                .addComponent(behandelingButton)
                .addGap(40, 40, 40)
                .addComponent(roosterButton)
                .addGap(40, 40, 40)
                .addComponent(geplandeButton)
                .addGap(40, 40, 40)
                .addComponent(cumulatiefButton)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void praktijkButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_praktijkButtonActionPerformed
        new PraktijkOverzichtGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_praktijkButtonActionPerformed

    private void behandelingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_behandelingButtonActionPerformed
        new OverzichtGUI().setVisible(true);
        dispose();
    }//GEN-LAST:event_behandelingButtonActionPerformed

    private void roosterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roosterButtonActionPerformed
        new RoosterGUI().setVisible(true);
        dispose();      
    }//GEN-LAST:event_roosterButtonActionPerformed

    private void geplandeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geplandeButtonActionPerformed
        new PlanningGUI().setVisible(true);
        dispose();    
    }//GEN-LAST:event_geplandeButtonActionPerformed

    private void cumulatiefButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cumulatiefButtonActionPerformed
        new CumulatiefGUI().setVisible(true);
        dispose();  
    }//GEN-LAST:event_cumulatiefButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton behandelingButton;
    private javax.swing.JButton cumulatiefButton;
    private javax.swing.JButton geplandeButton;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JButton praktijkButton;
    private javax.swing.JButton roosterButton;
    private javax.swing.JButton therapeutenButton;
    // End of variables declaration//GEN-END:variables
}
