/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package home.boundary;

import behandel.boundary.OverzichtGUI;
import behandel.control.BehandelingManager;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import praktijk.boundary.PraktijkOverzichtGUI;
import praktijk.control.PraktijkManager;
import praktijk.control.TherapeutManager;
import rapportage.boundary.CumulatiefGUI;
import rapportage.boundary.PlanningGUI;
import rapportage.boundary.RoosterGUI;

/**
 *
 * @author Leon
 */
public class HomeGUI extends javax.swing.JFrame {

    /**
     * Therapeut/Praktijk managers
     */
    private TherapeutManager therapeutManager;
    private PraktijkManager praktijkManager;
    
    /**
     * Behandeling manager
     */
    private BehandelingManager behandelingManager;
    
    /**
     * Creates new form HomeGUI
     */
    public HomeGUI(TherapeutManager therapeutManager, PraktijkManager praktijkManager, BehandelingManager behandelingManager) {
        this.therapeutManager = therapeutManager;
        this.praktijkManager = praktijkManager;
        this.behandelingManager = behandelingManager;
        
        initComponents();
        addWindowListener(new WindowAdapter() {
            @Override
            public void windowClosing(WindowEvent e) {
                sluitAf();
            }
        });
    }
    
    /**
     * Maak de GUI weer zichtbaar & zet het scherm in het midden
     */
    public void maakZichtbaar() {
        setVisible(true);
        setLocationRelativeTo(null);
    }
    
    /**
     * Sluit de applicatie af
     */
    public void sluitAf() {
        setVisible(false);
        AfsluitGUI afsluitGUI = new AfsluitGUI(behandelingManager);
        afsluitGUI.setVisible(true);
        afsluitGUI.sluitAf();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton3 = new javax.swing.JButton();
        behandelingOverzichtButton = new javax.swing.JButton();
        praktijkOverzichtButton = new javax.swing.JButton();
        therapeutenOverzichtButton = new javax.swing.JButton();
        geplandeBehandelingenButton = new javax.swing.JButton();
        roosterTherapeutenButton = new javax.swing.JButton();
        cumulatiefOverzichtButton = new javax.swing.JButton();

        jButton3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButton3.setText("Praktijk Overzicht");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);

        behandelingOverzichtButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        behandelingOverzichtButton.setText("Behandeling Overzicht");
        behandelingOverzichtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                behandelingOverzichtButtonActionPerformed(evt);
            }
        });

        praktijkOverzichtButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        praktijkOverzichtButton.setText("Praktijk Overzicht");
        praktijkOverzichtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                praktijkOverzichtButtonActionPerformed(evt);
            }
        });

        therapeutenOverzichtButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        therapeutenOverzichtButton.setText("Therapeuten Overzicht");
        therapeutenOverzichtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                therapeutenOverzichtButtonActionPerformed(evt);
            }
        });

        geplandeBehandelingenButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        geplandeBehandelingenButton.setText("Overzicht Geplande Behandelingen");
        geplandeBehandelingenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geplandeBehandelingenButtonActionPerformed(evt);
            }
        });

        roosterTherapeutenButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        roosterTherapeutenButton.setText("Rooster Fysiotherapeuten");
        roosterTherapeutenButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roosterTherapeutenButtonActionPerformed(evt);
            }
        });

        cumulatiefOverzichtButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        cumulatiefOverzichtButton.setText("Cumulatief Overzicht Behandelingen");
        cumulatiefOverzichtButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cumulatiefOverzichtButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(praktijkOverzichtButton, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(behandelingOverzichtButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(geplandeBehandelingenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(cumulatiefOverzichtButton, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(therapeutenOverzichtButton, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE)
                    .addComponent(roosterTherapeutenButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 372, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(praktijkOverzichtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(therapeutenOverzichtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(behandelingOverzichtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(roosterTherapeutenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(geplandeBehandelingenButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cumulatiefOverzichtButton, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void praktijkOverzichtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_praktijkOverzichtButtonActionPerformed
        new PraktijkOverzichtGUI(this, praktijkManager).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_praktijkOverzichtButtonActionPerformed

    private void therapeutenOverzichtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_therapeutenOverzichtButtonActionPerformed
        // Waar is deze?
    }//GEN-LAST:event_therapeutenOverzichtButtonActionPerformed

    private void behandelingOverzichtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_behandelingOverzichtButtonActionPerformed
        new OverzichtGUI(this, behandelingManager).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_behandelingOverzichtButtonActionPerformed

    private void roosterTherapeutenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roosterTherapeutenButtonActionPerformed
        new RoosterGUI(this, behandelingManager).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_roosterTherapeutenButtonActionPerformed

    private void geplandeBehandelingenButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_geplandeBehandelingenButtonActionPerformed
        new PlanningGUI(this, behandelingManager).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_geplandeBehandelingenButtonActionPerformed

    private void cumulatiefOverzichtButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cumulatiefOverzichtButtonActionPerformed
        new CumulatiefGUI(this, behandelingManager).setVisible(true);
        setVisible(false);
    }//GEN-LAST:event_cumulatiefOverzichtButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new HomeGUI().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton behandelingOverzichtButton;
    private javax.swing.JButton cumulatiefOverzichtButton;
    private javax.swing.JButton geplandeBehandelingenButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton praktijkOverzichtButton;
    private javax.swing.JButton roosterTherapeutenButton;
    private javax.swing.JButton therapeutenOverzichtButton;
    // End of variables declaration//GEN-END:variables
}
